version: '3'
services:
  tests:
    build: .
    volumes:
      - ".:/root/.vim/bundle/taskwiki:ro"
    network_mode: "host"
    security_opt:
      - label=type:container_runtime_t
    tty: true
    environment:
      COVERALLS_PARALLEL:
      COVERALLS_SERVICE_NAME:
      GITHUB_ACTIONS:
      GITHUB_HEAD_REF:
      GITHUB_REF:
      GITHUB_RUN_ID:
      GITHUB_RUN_NUMBER:
      GITHUB_SHA:
      GITHUB_TOKEN:
      PYTEST_FLAGS: "-o cache_dir=/tmp/pytest-cache ${PYTEST_FLAGS:-}"
