name: Release
on:
  release:
    types: [created]

jobs:
  build_and_upload_assets:
    name: Build and upload binary assets
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - node-version: 14
          - os: macos-latest
            target: macos
            asset_name: vim-doge-macos.tar.gz
            asset_path: ./bin/vim-doge-macos.tar.gz
          - os: ubuntu-latest
            target: linux
            asset_name: vim-doge-linux.tar.gz
            asset_path: ./bin/vim-doge-linux.tar.gz
          - os: windows-latest
            target: win
            asset_name: vim-doge-win64.zip
            asset_path: ./bin/vim-doge-win64.zip
    runs-on : ${{ matrix.os }}
    steps:
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save
      - name: Build Unix binary
        if: matrix.target != 'win'
        run: npm run build:binary:unix -- vim-doge-${{ matrix.target }}
      - name: Build Windows binary
        if: matrix.target == 'win'
        run: npm run build:binary:windows -- vim-doge-${{ matrix.target }}64
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ matrix.asset_path }}
          asset_name: ${{ matrix.asset_name }}
          asset_content_type: application/zip
